server:
  port: 9004
spring:
  application:
    name: ribbon #当前服务名称，注册到Eureka server上的名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/ #注册中心的访问地址
  instance:
    prefer-ip-address: true #是否将当前服务的ip注册到eureka server中