server:
  port: 10000
spring:
  profiles:
    active:
    - dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/ #注册中心的访问地址
  instance:
    prefer-ip-address: true #是否将当前服务的ip注册到eureka server中
---
spring:
  profiles: dev
  application:
    name: github-client-config-dev
---
spring:
  profiles: test
  application:
    name: github-client-config-test
