server:
  port: 10000
spring:
  profiles:
    active: 
      - dev
---
spring:
  profiles: dev
  application:
    name: github-client-config-dev
---
spring:
  profiles: test
  application:
    name: github-client-config-test11111333333
